### ISSUE TITLE
unpack requires a buffer of X bytes

### ISSUE THREAD

**Issue by daveisfera** [GeospatialPython/pyshp#134]
I'm trying to load a file and I got this stacktrace:
```
  File "/usr/src/app/shapefile.py", line 119, in extract_records
    for i, shapeRec in enumerate(self.sf.shapeRecords()):
  File "/usr/local/lib/python3.6/site-packages/shapefile.py", line 613, in shapeRecords
    for rec in zip(self.shapes(), self.records())]
  File "/usr/local/lib/python3.6/site-packages/shapefile.py", line 585, in records
    r = self.__record()
  File "/usr/local/lib/python3.6/site-packages/shapefile.py", line 504, in __record
    recordContents = self.__recStruct.unpack(f.read(self.__recStruct.size))
struct.error: unpack requires a buffer of 14091 bytes
```

**Comment by leviathan747** [comment]
Is there any resolution to this? I am hitting the same message.

**Comment by leviathan747** [comment]
Disregard. I had a corrupted shapefile

**Comment by ewrwrnjwqr** [comment]
bit late any resolution yet I im hitting a struct.error: unpack requires a buffer of 4380480 bytes error message

**Comment by karimbahgat** [comment]
This happens because the reader expects to read another record from the dbf file, but suddenly reaching the end of the file. This is likely due to a corrupt file, e.g. either the dbf header listing the wrong number of records, the dbf header listing the wrong byte length of each record, or the dbf file was interrupted/not completed when it was being written to disk. 

To know for sure, could you upload the shapefile that's causing the error, and say which pyshp version you're using? Does it work to open the shapefile in another GIS software?

**Comment by ewrwrnjwqr** [comment]
Sure, this is not a GIS project. But this error is uncommon as far I can see on the internet — processing RAW image frames — so when I found this I was wondering if someone found a solution. Specifically, my error was "struct.error: unpack requires a buffer of 4380480 bytes"

I am using this header hd0.32k and several raw files (below) to produce a DNG file using this library...

DNG library 
https://github.com/schoolpost/PiDNG/tree/master/pidng

hd0.32k header
[hd0.32k.zip](https://github.com/GeospatialPython/pyshp/files/7961339/hd0.32k.zip)

RAW photo file
[out.0001.raw.zip](https://github.com/GeospatialPython/pyshp/files/7961340/out.0001.raw.zip)

**Comment by karimbahgat** [comment]
I see, so you're not using the pyshp library, you're just getting a similar error message in the context of working with image formats. The only thing i could say is that the error comes from Python's builtin struct library, and happens when it's trying to read X bytes, but is only given <X bytes as input. There's no general solution to this problem, it just means there's a bug with you image format reader, or that the image you have is corrupt. You should probably submit an issue to the image reader library you're using.

**Comment by karimbahgat** [comment]
Closing since this type of error is most likely due to a corrupt file.
