### ISSUE TITLE
Maintenance of package?

### ISSUE THREAD

**Issue by megies** [GeospatialPython/pyshp#145]
@karimbahgat, @GeospatialPython it seems that this package has not been maintenanced in over half a year. There are some pull requests that have not been commented on by the maintainers in months, in the worst case in over 8 months.

This situation is really discouraging both for (potential) new users as well as people willing to send patches via pull requests in order to fix bugs and problems.

Do you need help with maintenance of the package?

**Comment by karimbahgat** [comment]
Hi @megies. Thanks for reaching out. You're absolutely right, and this is entirely on me. I started a series of changes for a new major version 2.0, and since then have gotten a bit too busy with other things (work++). 

Personally, I think it would be great with another set of hands on this project, if that is something you are interested in. Given PyShp's popularity in the Python GIS world, I agree and think more maintainers will help avoid activity lulls like this in the future. I'll wait to see what @GeospatialPython says. 

Until then, I am going to sit down and look at the issues and PRs right now, as well as finish the changes I started for v2.0. Once v2.0 is official it should also be easier to handle the issues and PRs as they come in.

**Comment by megies** [comment]
Thanks for the quick feedback. "Other things" is usually the problem and I totally understand. Are these v2.0 changes you mentioned visible somewhere already?

**Comment by karimbahgat** [comment]
Yeah, ‘other things’ and open source dont always go well together unfortunately :P 

The v2.0 changes is basically all the most recent changes in the main github branch, since the last year or so, specifically «2.0.0-dev». Until it’s all hashed out, the pypi version remains stable at 1.2 something. 

V2 includes a few incompatible changes like new ways of adding shapes, streamed file writing, ++.

**Comment by karimbahgat** [comment]
@GeospatialPython I tried seeing if I could add @megies as a maintainer (if he still wants), but I don't have access to the repository's settings tab. If you are okay with more maintainers, would you be able to do it?

**Comment by karimbahgat** [comment]
Just a quick update here that v2.0.0 is now officially released on PyPI.
