### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by kmacdonell** [GeospatialPython/pyshp#172]
I've processed ALL the County shape files for the US States (not sure why there is a state called Dakota, but this is not my point.)

ONLY in the New Mexico county file do I get an error processing it.  ALL the other county files have worked fine.  I get the following error:
@main[89]: Processing New Mexico...
@main[96]: mkdir /Users/kevin/dev/workspace/GED/SHF/NM
@main[106]: County shape file URL: https://www2.census.gov/geo/tiger/TIGER2010/COUNTY/2010/tl_2010_35_county10.zip
@main[109]: wget(https://www2.census.gov/geo/tiger/TIGER2010/COUNTY/2010/tl_2010_35_county10.zip, out=/Users/kevin/dev/workspace/GED/SHF/NM.zip)
100% [............................................................................] 673191 / 673191
@main[113]: unzip -d /Users/kevin/dev/workspace/GED/SHF/NM /Users/kevin/dev/workspace/GED/SHF/NM.zip
@main[124]: sfr = shapefile.Reader(/Users/kevin/dev/workspace/GED/SHF/NM/tl_2010_35_county10)
@main[142]: State: New Mexico, record 20: 'utf-8' codec can't decode byte 0xf1 in position 2: invalid continuation byte.

There are 33 counties in New Mexico, so the package couldn't read that far.

This happens as I start to read the records from the file.
                for i, rec in enumerate(sfr.records()):
                    county_name = rec[4]
                    logging.info(f"\t{i:>4} {rec[4]}")
                    state2county_map[state_key]['counties'].add(county_name)

So I'm guessing that the census bureau made a bad file, but if 50+ other files are OK, wondering if there is an edge case in this package.  I don't know enough to debug this myself.

**Comment by ohnorobo** [comment]
I think your issue is because tl_2010_35_county10.dbf contains 'Doña Ana County' as a field, which seems to be the only US county with a non-ascii name.

I've also been seeing these errors when trying to deal with non-ascii fields. The error is coming from the encode call at shapefile.py:136.

The unicode handling code around there seems to have been unchanged for a while, but maybe something changed somewhere else in this package to cause the issue more recently?

**Comment by karimbahgat** [comment]
That would make sense yes, there was a change in recent versions raising errors on non-ascii field names since the shapefile spec restricts this to ascii. However, it seems both ArcGIS and GDAL support it and it seems to be in popular demand, so adding back non-ascii field name support in the next version.

**Comment by karimbahgat** [comment]
Included now in version 2.1.0
