### ISSUE TITLE
Add an option to return 'date' as 'string' for easy conversion to geojson.

### ISSUE THREAD

**Issue by rados** [GeospatialPython/pyshp#187]
Hello,

Currently I am converting shape file to a geojson. In my shape file there are dates and I have to pay special attention to convert those dates to strings in order to json-ify them. So this could be a kind of common operation and then maybe the best thing is for the pyshp library to support this inherently somehow. Probably with a kind of flag or something better. I think this could be a simple change in the Reader.__record method, 'D' case.

I am ready to help with a PR.

Thanks,
Rado

**Comment by cipri-tom** [comment]
I am having the same problem.

@rados  are you doing any manual conversion, or just using the `.__geo_interface__` on the file reader ? 

How do you find the dates after the conversion ?

Thank you !

**Comment by karimbahgat** [comment]
Just pushed new commits to address this, no custom args needed. Date fields are loaded into python date objects for convenience to the user as usual, but calls to geo_interface will automatically convert them back to the original date string, so that they are directly able to be json serialized. Added tests to ensure that all geo_interface calls can be dumped to json. 

Based on your suggestion @cipri-tom I also ensured faulty date formats (those that end in the except clause) are converted to unicode/string. 

Until I push a new release version, you can try it out from the latest Github version.
