### ISSUE TITLE
How to delete a polygon in shp file based on field data?

### ISSUE THREAD

**Issue by geowat** [GeospatialPython/pyshp#190]
To remove a record from shp file using position is usually done with this code e.g. first record

```
e = shapefile.Editor('example.shp')
e.delete(0)
e.save('example')
```
But how can I delete a certain record by checking whether field contains certain data, e.g. 

```
r = shapefile.Reader('example.shp')
for idx, rec in enumerate(r.records()):
    nodenumber = rec[-1]
    if nodenumber == 999:
        ''' delete record '''
```

**Comment by fiveham** [comment]
There may be a more efficient way to do it, but here's one way: Iterate once over the records and record in a list the indices you wish to delete, then iterate backwards over that list, deleting each item.

    def my_test(record):
        '''custom record-checking code goes here'''
    
    delete_us = [rec.oid for rec in shapefile.Reader('example.shp') if my_test(rec)]
    with shapefile.Editor('example.shp') as e:
        for index in reversed(delete_us):
            e.delete(index)

**Comment by karimbahgat** [comment]
Yes, I believe that would be the way to do it. Also note that this is only for the older v1.x. 

In the newer 2.x, the Editor has been removed in order to remove the footprint, so you would have to do it by iterating the reader, and copying over each shape/record one-by-one, except the ones you want to delete. I think something like this would work (for pyshp v2.x):

```
with shapefile.Reader('example.shp') as r:
    with shapefile.Writer('example_deleted.shp') as w:
        for shaperec in r:
            if shaperec.record.as_dict()['some_field'] == 'meets some criteria':
                w.shape(shaperec.shape)
                w.record(*shaperec.record)
```
