### ISSUE TITLE
__geo_interface__ not JSON serializable

### ISSUE THREAD

**Issue by giswqs** [GeospatialPython/pyshp#208]
I am trying to convert a shapefile to geojson using  `__geo_interface__`. The geojson dict can be printed correctly. However, I got a `TypeError: Object of type _Array is not JSON serializable` when trying to save the geojson. 

```
import shapefile, json
sf = shapefile.Reader("path/to/shapefile")
with open("poly.geojson", "w") as f:
    f.write(json.dumps(sf.__geo_interface__))
```

**Comment by karimbahgat** [comment]
Yes, that is due to the Reader geo interface adds a bbox entry to the output geojson, based on the Reader.bbox which is an _Array list subclass and is therefore not JSON serializable. I just recently added tests for geojson json dump and noticed the same, adding a fix in https://github.com/GeospatialPython/pyshp/commit/7ef3456521be80c699d06d802adec176ca2b9169. Can you try again with the current GitHub codebase and see if that fixes it?

**Comment by giswqs** [comment]
@karimbahgat Thank you for the quick fix. It works like a charm now.
