### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'S'

### ISSUE THREAD

**Issue by beamerblvd** [GeospatialPython/pyshp#23]
When loading the Quattroshapes (Foursquare) localities shapefiles (http://static.quattroshapes.com/qs_localities.zip) and calling `s.record(0)`, I get the following error:

```
ValueError: invalid literal for int() with base 10: 'S'
```

~~This stems from the fact that, for whatever reason, `null` numeric values in this shapefile are "S*********" instead of "**********".~~

~~Pull request coming soon.~~

**Comment by beamerblvd** [comment]
Well I thought that was the problem, but the problem appears to be bigger. As I debug through the file, here are the values of the first several type `N` fields:

    S******
    US*****
     US****
      US***
       US**
        US*
         US
          U

And etc. Clearly there's some type of issue reading this entire fileset.

**Comment by karimbahgat** [comment]
After several datatype bugfixes, this issue seems to have been partially resolved, as calling record(0) on the qs_localities file now works without causing an error, as does iterating through every single record. 

However, I also got those strange values with offsets and asterixes. It is not a matter of a corrupt file since eg QGIS reads the values fine without all the weirdness. Interestingly, those fields you mention contain text and should therefore not be type "N" (numeric). According to QGIS the file only contains "S" string and "I" integer fields, whereas PyShp wrongly interprets some of them as "N" numeric, which is probably the likely culprit, reading the wrong number of bytes for each value. 

So this definitively deserves a closer inspection at some point, and PyShp's parsing of the dbf fieldtypes in the header is probably a good place to start.

**Comment by karimbahgat** [comment]
After some more digging, finally got to the bottom of this. 

Parsing of field types was not the issue (the QGIS int was simply a way of saying Numeric with 0 decimals). Instead, I checked whether each record read the correct number of bytes that it should, but then I noticed that the recordsize from the header was not being checked. The format and size was based purely on the field definitions, so when I compared this with the supposed recordlength it seemed the recordlength was supposed to be 1 byte longer, causing the incremental offsets. 

It appears whatever writer wrote the qs_localities.shp file somehow overestimated the total record length and padded each record to remain true to it. Our solution then is to assume the record length in the header is the correct size, which fixed the problem of incremental offsets. See #92. 

The file still does not read correctly however, since every record value seems to be offset by exactly 1 byte (hence the * in front of several values, and "USA" split into " US" and "A...". It seems the original writer added the padding at the beginning of each record rather than the end, but the correct behavior is probably to assume the padding is at the end, since QGIS seems to do it like that (QGIS gets same results as this PR). This remaining issue will just have to be blamed on a badly written (corrupt) file.
