### ISSUE TITLE
shapes and records are not pickable 

### ISSUE THREAD

**Issue by pooya-mohammadi** [GeospatialPython/pyshp#238]
records that are created using shapefile.Reader are pickable. I want to do a series of processes with multiprocessing but shapes does not become pickle objects and process fails.
```
import shapefile
import pickle

counties = shapefile.Reader("counties.shp")
records = counties.records()

buf = pickle.dumps(records[0])
record_0 = pickle.loads(buf)
```
Error message:
```
[Previous line repeated 995 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by karimbahgat** [comment]
From your code example, the part that fails is trying to pickle a record. Can you clarify if it's records or shapes that fail to pickle? 

Either way, the error looks to be an [issue of highly recursive class structures](https://stackoverflow.com/questions/2134706/hitting-maximum-recursion-depth-using-pickle-cpickle), though not sure why the Shape class would be recursive, it simply contains attributes of flat lists and a few string/int attributes. 

For your use case however i would just suggest dumping to a json string instead of pickling, which is easier to work with and can easily be turned back into a Shape instance if needed:

```
import json
reader = ...
shape = reader.shape(0)
shape_geojson_string = json.dumps(shape.__geo_interface__)
# send to multiprocessing
# ...
```

**Comment by pooya-mohammadi** [comment]
@karimbahgat 
shapes are fine but the records are not pickable. I don't directly pickle them. Multiprocessing library pickles each task and sends it to a random worker.
