### ISSUE TITLE
Python 3.4.3 Error : invalid literal for int() with 10: floatvalue

### ISSUE THREAD

**Issue by apiszcz** [GeospatialPython/pyshp#28]
Version 1.2.1 20140507

The following line is throwing a stack track with the subject error message:

Line 501
value = int(value)

My quick fix is 
value = int(float(value))

However there may be other areas where this type of conversion fails with python 3.

Review my field definition it is an integer though the incoming value is a float, will change my field spec fiction to a float

It appears this line# is 506 with latest version.

**Comment by karimbahgat** [comment]
This appears to have been fixed. It still says value = int(value), but a try clause has been added so that the value is set to None upon fail rather than throwing an exception. 

If it changed to int(float(value)) then float values would be rounded downwards to ints which is questionable behavior, and besides such a scenario shouldn't be possible since the code is only run for numeric field types with decimal set to 0.
