### ISSUE TITLE
pyshp 1.21 unable to write double values for an attribute

### ISSUE THREAD

**Issue by apiszcz** [GeospatialPython/pyshp#7]
Using a double attribute for a field causes a save error.

```
e.save(srcpath)
```

  File "lib\shapefile.py", line 1042, in save
    self.saveDbf(target)
  File "lib\shapefile.py", line 1014, in saveDbf
    self.__dbfRecords()
  File "lib\shapefile.py", line 901, in __dbfRecords
    assert len(value) == size
AssertionError

**Comment by karimbahgat** [comment]
So the original issue here was caused by the field length being too short for the value. 

Another issue was that `w.record(DOUBLETEST=1234567890123.0)` was mistyped as `w.record('DOUBLETEST',1234567890123.0)`. 

As for the doc additions, I didn't fully understand which parts were desired, but record keyword assignment are already featured in the docs, and #73 suggests adding more examples on data types. 

And the assert has been changed to a more informative exception. 

Considering this resolved.
