### ISSUE TITLE
Fields don't align to record values

### ISSUE THREAD

**Issue by achapkowski** [GeospatialPython/pyshp#90]
Hello,
I have a simple example:

        reader = shapefile.Reader(filename)
        fields = [field[0] for field in reader.fields]
        for r in reader.iterShapeRecords():
            print(dict(zip(fields, r.records)))
            break
        del reader

The records are not aligning up to the field names.  Is there a way to ensure field values match up field names?

For example, I have a STATE_FIPS field, it should be numeric value, but it's a string value.  

What is the proper way to do this?

Thanks

**Comment by GeospatialPython** [comment]
When you access the ```reader.fields``` variable, it includes a "hidden" field called "DeletionFlag" which is a feature of the ancient DBF format.  The ```record``` variable doesn't include that column.  So you're getting a shift due to mismatched column sizes.

To modify your example in the simplest way, just ignore that first column:

```
    reader = shapefile.Reader(filename)
    fields = [field[0] for field in reader.fields[1:]]
    for r in reader.iterShapeRecords():
        print(dict(zip(fields, r.record)))
```

Also you don't need the ```del reader``` and ```break``` statements since this is all pure Python.

**Comment by achapkowski** [comment]
@GeospatialPython Thank you for the information.  I wasn't sure if there was a way to prevent the extra field from not showing.
